"""add unique constraints

Revision ID: 1ee8bf053b59
Revises: 
Create Date: 2026-08-13 00:19:27.054871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee8bf053b59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    op.create_unique_constraint('unique_usernames', 'users', ['username'])
    op.create_unique_constraint('unique_emails', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_usernames', 'users', type_='unique')
    op.drop_constraint('unique_emails', 'users', type_='unique')
    op.drop_column('notes', 'updatedAt')
    # ### end Alembic commands ###
